name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: display_information_1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.MATRICS }}
          user: slowy07
          # template
          template: classic
          # base
          base: activity, community, repositories, metadata
          # timezone
          config_timezone: Asia/Jakarta
          # filename
          filename: github-metrics.svg
          # repositories batch
          repositories_batch: 7
          # repositories limit
          repositories: 100
          # topics
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          # recent activity
          plugin_activity: yes
          plugin_activity_limit: 1
          plugin_activity_days: 14
          plugin_activity_filter: all
          config_padding: 0, 6 + 1%

      - name: most used
        uses: lowlighter/metrics@latest
        with:
          filename: programming.languages.svg
          token: ${{ secrets.MATRICS }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          config_padding: 0, 8 + 1%
          
          
          
      # notable contrib
      - name: display_contribution
        uses: lowlighter/metrics@latest
        with:
          filename: contribution.svg
          token: ${{ secrets.MATRICS }}
          user: slowy07
          base: metadata
          repositories_batch: 3
          plugin_notable: yes
          plugin_notable_repositories: no
          config_padding: 0, 8 + 1%

      #achievements
      # - name: display_achivement
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: achievements-metrics.svg
      #     token: ${{ secrets.MATRICS }}
      #     base: ""
      #     plugin_achievements: yes
      #     plugin_achievements_display: compact
      #     config_display: large
